version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "euan-cowie"
    assignees:
      - "euan-cowie"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      go-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "golang.org/x/*"
      go-stdlib:
        patterns:
          - "golang.org/x/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "euan-cowie"
    assignees:
      - "euan-cowie"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"