run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/euan-cowie/cidrator
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive # replacement for golint
    - mnd # replacement for gomnd
    - copyloopvar # replacement for exportloopref
    - shadow # replacement for govet's check-shadowing

issues:
  exclude-rules:
    - path: cmd/.*\.go
      linters:
        - gochecknoinits # Allow init in cmd package for cobra
    - path: _test\.go
      linters:
        - mnd # Exclude magic number detection in tests
        - funlen # Don't be too strict on test function length

  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
