# Modern pre-commit hooks for Go projects
# Install: make install-precommit
# Remove: make remove-precommit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go formatting
      - id: go-fmt-repo
      - id: go-vet-repo-mod
      - id: go-mod-tidy-repo

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.8
    hooks:
      - id: golangci-lint
        args: [--fast]

# This is fast, reliable, and follows Go best practices
# Most checks complete in under 10 seconds
