blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/euan-cowie/cidrator/discussions
    about: Ask questions, share ideas, and discuss features with the community
  - name: 📖 Documentation & Wiki
    url: https://github.com/euan-cowie/cidrator/wiki
    about: Check our comprehensive documentation and guides
  - name: 🔒 Security Vulnerabilities
    url: https://github.com/euan-cowie/cidrator/security/advisories
    about: Report security vulnerabilities privately through GitHub Security Advisories
  - name: 📧 Security Email
    url: mailto:security@cidrator.dev
    about: Alternative private security reporting via email 